shared:
  image: golang:latest

jobs:
  binary:
    steps:
      - publish: sd-cmd publish -f binary-command.yaml
      # default pipe size: 64KB (65536)
      # see http://man7.org/linux/man-pages/man7/pipe.7.html
      - exec: dd if=/dev/zero bs=65537 count=1 | sd-cmd exec screwdriver-cd-test/binary-func-test@1 foo bar

  habitat:
    steps:
      - publish: sd-cmd publish -f habitat-command.yaml
      - exec: sd-cmd exec screwdriver-cd-test/habitat-func-test@1 -v

  publish-stable:
    steps:
      - publish: sd-cmd publish -f promote-command.yaml -t stable

  publish-latest:
    steps:
      - publish: sd-cmd publish -f promote-command.yaml

  promote:
    steps:
      - promote: sd-cmd promote screwdriver-cd-test/promote-func-test 1.0.1 stable
      - release: sd-cmd promote screwdriver-cd-test/promote-func-test stable GA

  validate-valid:
    steps:
      - sd-cmd validate -f binary-command.yaml

  validate-invalid:
    steps:
      - sd-cmd validate -f sd-invalid-command.yaml

  publish-trusted:
    steps:
      - sd-cmd publish -f sd-trusted-command.yaml

  publish-distrusted:
    steps:
      - sd-cmd publish -f sd-distrusted-command.yaml

