shared:
  image: golang:latest

jobs:
  binary:
    steps:
      - publish: sd-cmd publish -f binary-command.yaml
      - exec: sd-cmd exec screwdriver-cd-test/binary-test@1 foo bar

  habitat:
    steps:
      - publish: sd-cmd publish -f habitat-command.yaml
      - exec: sd-cmd exec screwdriver-cd-test/habitat-test@1 -v

  publish-stable:
    steps:
      - publish: sd-cmd publish -f promote-command.yaml -t stable

  publish-latest:
    steps:
      - publish: sd-cmd publish -f promote-command.yaml

  promote:
    steps:
      - promote: sd-cmd promote screwdriver-cd-test/promote-test 1.0.1 stable
      - release: sd-cmd promote screwdriver-cd-test/promote-test stable GA
